# AutPGrp, chapter 4
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("autpgrp03.tst");

# doc/influen.xml:198-207
gap> G := PcGroupCode( 103045690560068391423508120999240094531550914947096312619671359, 512 );;
gap> SetInfoLevel( InfoAutGrp, 0 );
gap> A := AutomorphismGroupPGroup( G : OrbitLimit := 1000 );;
gap> A.size;
262144
gap> H := PcGroupCode( 216782169967590115555, 729 );;
gap> AutomorphismGroupPGroup( H : OrbitLimit := 2 );
fail

#
gap> STOP_TEST("autpgrp03.tst", 1);
