gap> START_TEST("hybridrecord.tst");

# Hybrid records supplied by other packages (see anupq#67): the ag part
# must be normal and glOper must represent A/S.  Here aut1 lies in the
# group generated by the gl part, so the record double-counts.
gap> G := AbelianGroup([2,2,2,2]);;
gap> aut1 := PGAutomorphism( G, [ G.1, G.2, G.3, G.4 ], [ G.1*G.2*G.3*G.4, G.1*G.4, G.3*G.4, G.3 ] );;
gap> aut2 := PGAutomorphism( G, [ G.1, G.2, G.3, G.4 ], [ G.3, G.1*G.2*G.4, G.2*G.4, G.1*G.3*G.4 ] );;
gap> aut3 := PGAutomorphism( G, [ G.1, G.2, G.3, G.4 ], [ G.2, G.2*G.3*G.4, G.2*G.3, G.1*G.2 ] );;
gap> one  := PGAutomorphism( G, [ G.1, G.2, G.3, G.4 ], [ G.1, G.2, G.3, G.4 ] );;
gap> aut1!.mat := ImmutableMatrix(GF(2), Z(2)*[[0,1,0,0,0,0],[1,1,0,0,0,0],[0,1,1,1,1,1],[1,1,1,0,0,1],[0,0,0,0,1,1],[0,0,0,0,1,0]]);;
gap> aut2!.mat := ImmutableMatrix(GF(2), Z(2)*[[1,0,0,0,0,0],[1,1,0,0,0,0],[0,0,0,0,1,0],[1,1,1,1,0,1],[1,0,0,1,0,1],[1,0,1,0,1,1]]);;
gap> aut3!.mat := ImmutableMatrix(GF(2), Z(2)*[[0,1,0,0,0,0],[1,1,0,0,0,0],[0,0,0,1,0,0],[0,1,0,1,1,1],[1,1,0,1,1,0],[1,0,1,1,0,0]]);;
gap> one!.mat := IdentityMat(6, GF(2));;
gap> elm := AsSet( GF(2)^4 );;
gap> permOf := a -> Permutation( ImmutableMatrix( GF(2), List( a!.baseimgs, x -> ExponentsOfPcElement( Pcgs(G), x ){[1..4]} ) * Z(2) ), elm, OnRight );;
gap> aut := rec( agAutos := [ aut1 ], agOrder := [ 3 ], field := GF(2),
>   glAutos := [ aut2, aut3 ], glOper := List( [ aut2, aut3 ], permOf ),
>   agOper := [ permOf( aut1 ) ], group := G, one := one );;
gap> aut.glOrder := Size( Group( aut.glOper ) );
360
gap> baseU := Z(2)*[[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]];;
gap> baseN := IdentityMat( 6, GF(2) );;
gap> PGOrbitStabilizer( aut, baseU, baseN, false );
Error, hybrid record: |A/S| = 120 differs from glOrder = 360

# the same record with glOrder = |A/S|, as ANUPQ now passes it
gap> P := Group( Concatenation( aut.glOper, aut.agOper ) );;
gap> aut.glOrder := Index( P, Subgroup( P, aut.agOper ) );
120
gap> PGOrbitStabilizer( aut, baseU, baseN, false );;
gap> aut.glOrder * Product( aut.agOrder );
6

# the same stabiliser without a soluble part
gap> aut := rec( agAutos := [ ], agOrder := [ ], field := GF(2),
>   glAutos := [ aut2, aut3 ], glOper := List( [ aut2, aut3 ], permOf ),
>   glOrder := 360, group := G, one := one );;
gap> PGOrbitStabilizer( aut, baseU, baseN, false );;
gap> aut.glOrder * Product( aut.agOrder );
6
gap> Size( Stabilizer( Group( [ aut2!.mat, aut3!.mat ] ), TriangulizedMat( baseU ), OnSubspacesByCanonicalBasis ) );
6

#
gap> STOP_TEST("hybridrecord.tst", 1);
