#############################################################################
##
#W  permstab.gi              AutPGrp package                        Max Horn
##
##  Stabilizer of a subspace as a set stabilizer in a permutation group,
##  delegated to GAP's Stabilizer.  Used when the gl orbit would be long.
##

#############################################################################
##
#F PGLineClosure( lines, mats, budget, dstate )
##
## The lines in the orbits of <lines> under the group generated by <mats>,
## as a sorted list, or fail if that takes more than <budget> vector-matrix
## products (counted over all calls sharing <dstate>) or more than
## PG_PERM_DOMAIN_LIMIT lines.  The closure computed so far is kept in
## <dstate> and continued by a later call.  Membership during the closure
## needs a dictionary; the result is sorted so that PositionSorted serves
## afterwards.
##
BindGlobal( "PGLineClosure", function( lines, mats, budget, dstate )
    local dom, dict, i, m, w;

    if not IsBound( dstate.dom ) then
        dstate.dom := List( lines, Immutable );
        dstate.dict := NewDictionary( dstate.dom[1], true );
        for i in [1..Length(dstate.dom)] do
            AddDictionary( dstate.dict, dstate.dom[i], i );
        od;
        dstate.next := 1;
    fi;
    dom := dstate.dom;
    dict := dstate.dict;
    # an identity action is stored as the integer 1, see LinearActionPGAut
    mats := Filtered( mats, x -> x <> 1 );

    i := dstate.next;
    while i <= Length( dom ) do
        if i * Length( mats ) > budget then
            dstate.next := i;
            Info( InfoAutGrp, 3, "    line closure not done within ",
                  budget, " products, ", Length( dom ), " lines so far" );
            return fail;
        fi;
        for m in mats do
            w := Immutable( NormedRowVector( dom[i] * m ) );
            if LookupDictionary( dict, w ) = fail then
                if Length( dom ) >= PG_PERM_DOMAIN_LIMIT then
                    dstate.next := i;
                    Info( InfoAutGrp, 3, "    line closure exceeds ",
                          PG_PERM_DOMAIN_LIMIT, " lines" );
                    return fail;
                fi;
                Add( dom, w );
                AddDictionary( dict, w, Length( dom ) );
            fi;
        od;
        i := i + 1;
    od;
    dstate.next := i;
    return Set( dom );
end );

#############################################################################
##
#F PGPermStabilizer( A, glMats, agMats, agAutos, os, pt, fpt, info, induce,
##                   budget, dstate )
##
## <A> acts on a section of the p-multiplicator through <glMats> (for
## A.glAutos) and <agMats> (for <agAutos>, a generating set of the ag part
## S); <pt> is a basis of a subspace of that section, <fpt> the action on
## such points, and <os> the record of PcgsOrbitStabilizer for <pt>.
## <induce> maps the matrix of an automorphism on the multiplicator to its
## action on the section.  Returns a record as BlockOrbitStabilizer does
## (stabl, pstab, length), or fail if this method cannot beat the
## enumeration or its permutation domain cannot be built within <budget>
## vector-matrix products and PG_PERM_DOMAIN_LIMIT points.  The domain
## built so far is kept in the record <dstate>, so a later call continues
## where this one stopped.
##
## A subspace is fixed by an element exactly when the set of its lines is.
## So Stab_A(pt) is the stabilizer of a finite set in a permutation action
## of A, which GAP's Stabilizer computes (for permutation groups by
## partition backtrack, RepOpSetsPermGroup in lib/stbcbckt.gi); its cost
## depends on the degree, not on the length of the orbit of pt.  Domain:
##
##     block 1: the points of A.glOper, a faithful rep of A/S on which S
##              acts trivially (the invariant of the hybrid record)
##     block 2: all lines of the section if there are few, otherwise the
##              lines in the A-orbits of the lines of pt
##
## The kernel of A on block 1 + block 2 lies in S and fixes pt, so the
## preimage of the set stabilizer T is exactly Stab_A(pt).  Restricting T
## to block 1 gives Stab_A(pt)/Stab_S(pt), which is exactly the gl part
## needed: Stab_S(pt) is already known.
##
## A generator t of T is lifted to an automorphism through block 1 alone,
## where A/S has a small degree: the preimage a of its restriction lies
## in the coset t S, so it maps pt into the S-orbit of pt, and the
## transversal of <os> moves it back to pt, as BlockOrbitStabilizer does.
##
InstallGlobalFunction( PGPermStabilizer,
  function( A, glMats, agMats, agAutos, os, pt, fpt, info, induce, budget,
            dstate )
    local d1, field, lines, m, dom, permOnDom, perms, P, set, T, Q,
          qhom, bdict, stabl, pstab, t, res, a, y, j, order, i;

    d1 := LargestMovedPoint( A.glOper );
    field := A.field;

    # a single line: its orbit is the domain, enumeration is as good
    lines := NormedRowVectors( VectorSpace( field, pt ) );
    if Length( lines ) = 1 then return fail; fi;

    # block 2, a sorted list of lines
    m := Length( pt[1] );
    if ( Size(field)^m - 1 ) / ( Size(field) - 1 ) <= PG_PERM_FULL_LIMIT then
        dom := NormedRowVectors( field^m );
    else
        dom := PGLineClosure( lines, Concatenation( glMats, agMats ),
                              budget, dstate );
        if dom = fail then return fail; fi;
    fi;
    Info( InfoAutGrp, 3, "    set stabilizer on ", d1, " + ", Length(dom),
          " points, set of size ", Length( lines ) );

    permOnDom := function( mat )
        if mat = 1 then return [1..Length(dom)]; fi;   # identity, see below
        return List( dom, v -> PositionSorted( dom, NormedRowVector( v * mat ) ) );
    end;

    # generators of A as perms on block 1 + block 2; the package stores an
    # identity action as the integer 1, see LinearActionPGAut
    perms := [];
    for i in [1..Length(glMats)] do
        Add( perms, PermList( Concatenation( ListPerm( A.glOper[i], d1 ),
                                             permOnDom( glMats[i] ) + d1 ) ) );
    od;
    for i in [1..Length(agMats)] do
        Add( perms, PermList( Concatenation( [1..d1],
                                             permOnDom( agMats[i] ) + d1 ) ) );
    od;
    perms := Filtered( perms, x -> not IsOne( x ) );
    if IsEmpty( perms ) then
        return rec( stabl := [], pstab := [], length := A.glOrder );
    fi;

    # the set stabilizer, by GAP
    P := Group( perms );
    set := List( lines, v -> d1 + PositionSorted( dom, v ) );
    Sort( set );
    T := Stabilizer( P, set, OnSets );

    # lift generators moving block 1; the others lie in Stab_S(pt)
    Q := Group( A.glOper, () );
    SetSize( Q, A.glOrder );
    qhom := GroupHomomorphismByImagesNC( Q, Group( A.glAutos, A.one ),
                                         A.glOper, A.glAutos );
    bdict := NewDictionary( os.orbit[1], true );
    for j in [1..Length(os.orbit)] do
        AddDictionary( bdict, os.orbit[j], j );
    od;
    stabl := [];
    pstab := [];
    for t in GeneratorsOfGroup( T ) do
        res := RestrictedPerm( t, [1..d1] );
        if IsOne( res ) then continue; fi;
        a := ImagesRepresentative( qhom, res );
        y := fpt( pt, induce( a!.mat ), info );
        j := LookupDictionary( bdict, y );
        Assert( 1, j <> fail );
        if j > 1 then
            a := PGMult( a, OSTransversalInverse( j, os.trans, os.trels, A.one ) );
        fi;
        Add( stabl, a );
        Add( pstab, res );
    od;

    if IsEmpty( pstab ) then
        order := 1;
    else
        order := Size( Group( pstab ) );
    fi;
    Assert( 1, A.glOrder mod order = 0 );
    return rec( stabl := stabl, pstab := pstab, length := A.glOrder / order );
end );
